### ISSUE TITLE
Closing panel when tapping anywhere over a body

### ISSUE THREAD

**Issue by Wassmd** [akshathjain/sliding_up_panel#66]
I did following. First time it is closing properly but second time it is throwing exception

```
import 'package:flutter/material.dart';
import 'package:sliding_up_panel/sliding_up_panel.dart';

class BottomSheetScreen extends StatefulWidget {
  @override
  _BottomSheetScreenState createState() => _BottomSheetScreenState();
}

class _BottomSheetScreenState extends State<BottomSheetScreen> {
  final AppBar appBar = AppBar(title: Text('Bottom sheet Demo'));
  double calculatePanelHeight(BuildContext context) {
    return MediaQuery.of(context).size.height -
        appBar.preferredSize.height -
        100;
  }

  @override
  Widget build(BuildContext context) {
    bool _shouldClose = false;
    PanelController _pc = new PanelController();

    return Scaffold(
      appBar: appBar,
      body: SlidingUpPanel(
        controller: _pc,
        maxHeight: calculatePanelHeight(context),
        borderRadius: BorderRadius.all(const Radius.circular(16.0)),
        backdropTapClosesPanel: _shouldClose,
        body: GestureDetector(
            onTap: () {
              print("Tapped detected..!!");
              setState(() {
                _pc.close();
              });
            },
            child: Text('This is main container',
                style: TextStyle(color: Colors.white))),
        panel: Container(
          child: SafeArea(
              child: Column(
            children: <Widget>[
              Padding(
                  padding: EdgeInsets.all(10.0),
                  child: Text('This is bottom sheet',
                      style: TextStyle(color: Colors.black)))
            ],
          )),
        ),
      ),
    );
  }
}
```
Exception

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'call' was called on null.
Receiver: null
Tried calling: call()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      PanelController.close (package:sliding_up_panel/src/panel.dart:497:5)
#2      _BottomSheetScreenState.build.<anonymous closure>.<anonymous closure> (package:smart_parking_flutter/screens/bottom_sheet_demo.dart:37:21)
#3      State.setState (package:flutter/src/widgets/framework.dart:1141:30)
#4      _BottomSheetScreenState.build.<anonymous closure> (package:smart_parking_flutter/screens/bottom_sheet_demo.dart:32:15)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#e03d7
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(55.7, 107.0)
  finalLocalPosition: Offset(55.7, 7.0)
  sent tap down

```

**Comment by bullet-tooth** [comment]
@Wassmd have you solve this issue? If yes please provide a working solution. It would be very helpful for newbies like me :)
  Thanks!
